all:
	g++ -Wall -g -std=c++11 sort_gtf.cpp -o sort_gtf
	g++ -Wall -g -std=c++11 etching_fg_identifier.cpp -L../lib -l fg_identifier -o etching_fg_identifier

clean:
	rm -f etching_fg_identifier sort_gtf
