all:
	cd api && make
	cd api/internal/bam && make
	cd api/internal/index && make
	cd api/internal/io && make
	cd api/internal/sam && make
	cd api/internal/utils && make

clean:
	rm -f api/*.o api/internal/*/*.o

