default: BamDeviceFactory_p.cpp.o BamFile_p.cpp.o BamFtp_p.cpp.o BamHttp_p.cpp.o BamPipe_p.cpp.o BgzfStream_p.cpp.o ByteArray_p.cpp.o HostAddress_p.cpp.o HostInfo_p.cpp.o HttpHeader_p.cpp.o ILocalIODevice_p.cpp.o RollingBuffer_p.cpp.o TcpSocketEngine_p.cpp.o TcpSocketEngine_unix_p.cpp.o TcpSocket_p.cpp.o

BamDeviceFactory_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib BamDeviceFactory_p.cpp -o BamDeviceFactory_p.cpp.o
BamFile_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib BamFile_p.cpp -o BamFile_p.cpp.o
BamFtp_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib BamFtp_p.cpp -o BamFtp_p.cpp.o
BamHttp_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib BamHttp_p.cpp -o BamHttp_p.cpp.o
BamPipe_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib BamPipe_p.cpp -o BamPipe_p.cpp.o
BgzfStream_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib BgzfStream_p.cpp -o BgzfStream_p.cpp.o
ByteArray_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib ByteArray_p.cpp -o ByteArray_p.cpp.o
HostAddress_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib HostAddress_p.cpp -o HostAddress_p.cpp.o
HostInfo_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib HostInfo_p.cpp -o HostInfo_p.cpp.o
HttpHeader_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib HttpHeader_p.cpp -o HttpHeader_p.cpp.o
ILocalIODevice_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib ILocalIODevice_p.cpp -o ILocalIODevice_p.cpp.o
RollingBuffer_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib RollingBuffer_p.cpp -o RollingBuffer_p.cpp.o
TcpSocketEngine_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib TcpSocketEngine_p.cpp -o TcpSocketEngine_p.cpp.o
TcpSocketEngine_unix_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib TcpSocketEngine_unix_p.cpp -o TcpSocketEngine_unix_p.cpp.o
TcpSocket_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c -I../../../../zlib TcpSocket_p.cpp -o TcpSocket_p.cpp.o

clean:
	rm -f *.o
