default: BamDeviceFactory_p.cpp.o BamFile_p.cpp.o BamFtp_p.cpp.o BamHttp_p.cpp.o BamPipe_p.cpp.o BgzfStream_p.cpp.o ByteArray_p.cpp.o HostAddress_p.cpp.o HostInfo_p.cpp.o HttpHeader_p.cpp.o ILocalIODevice_p.cpp.o RollingBuffer_p.cpp.o TcpSocketEngine_p.cpp.o TcpSocketEngine_unix_p.cpp.o TcpSocket_p.cpp.o

BamDeviceFactory_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c BamDeviceFactory_p.cpp -o BamDeviceFactory_p.cpp.o
BamFile_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c BamFile_p.cpp -o BamFile_p.cpp.o
BamFtp_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c BamFtp_p.cpp -o BamFtp_p.cpp.o
BamHttp_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c BamHttp_p.cpp -o BamHttp_p.cpp.o
BamPipe_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c BamPipe_p.cpp -o BamPipe_p.cpp.o
BgzfStream_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c BgzfStream_p.cpp -o BgzfStream_p.cpp.o
ByteArray_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c ByteArray_p.cpp -o ByteArray_p.cpp.o
HostAddress_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c HostAddress_p.cpp -o HostAddress_p.cpp.o
HostInfo_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c HostInfo_p.cpp -o HostInfo_p.cpp.o
HttpHeader_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c HttpHeader_p.cpp -o HttpHeader_p.cpp.o
ILocalIODevice_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c ILocalIODevice_p.cpp -o ILocalIODevice_p.cpp.o
RollingBuffer_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c RollingBuffer_p.cpp -o RollingBuffer_p.cpp.o
TcpSocketEngine_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c TcpSocketEngine_p.cpp -o TcpSocketEngine_p.cpp.o
TcpSocketEngine_unix_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c TcpSocketEngine_unix_p.cpp -o TcpSocketEngine_unix_p.cpp.o
TcpSocket_p.cpp.o:
	g++ -Wall -std=c++11 -g -I ../../.. -fPIC -c TcpSocket_p.cpp -o TcpSocket_p.cpp.o

clean:
	rm -f *.o
